on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
      os:
        type: string
        description: 'Only run for specified OS'
        required: false
        default: "all"

name: test

jobs:
  test:
    runs-on: ${{ matrix.config.os }}

    defaults:
      run:
        shell: bash

    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest}
          - {os: windows-latest}
          - {os: ubuntu-latest}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: build and test
        if: ${{ matrix.config.os != "windows-lateste" }}
        run: make

      - name: build and test
        if: ${{ matrix.config.os == "windows-lateste" }}
        run: make CC=gcc

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled && (inputs.os == matrix.config.os || inputs.os == 'all') }}
        with:
          limit-access-to-actor: true
